package com.flowfin.core.designsystem.icon

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.material3.Icon
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.em
import androidx.compose.ui.unit.sp
import com.flowfin.core.designsystem.theme.FlowFinTheme

/**
 * FlowFin's icon language: thin line icons, deliberately not Material's filled
 * glyphs. Prefer these everywhere — resolved from category/account keys by
 * `categoryIcon()` in core/ui, or referenced directly for UI glyphs — and reach
 * for Material only when this set doesn't yet cover an icon.
 *
 * Each is a 24×24 stroke [ImageVector] (1.5dp, round caps/joins, no fill), drawn
 * to match the SVGs in design/system/icons.html. The stroke is an opaque
 * placeholder color, so an icon must be rendered through [Icon] for its `tint`
 * to apply; drawn untinted it shows the placeholder, not the color you intended.
 *
 * Generated by design/tools/gen_flowfin_icons.py — re-running it overwrites this
 * file, comment included, so make changes there (or keep them in sync).
 */
object FlowFinIcons {
  val Home: ImageVector by lazy { lineIcon("M3 10l9-7 9 7v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V10z") }
  val Accounts: ImageVector by lazy { lineIcon("M 5 6 L 19 6 A 2 2 0 0 1 21 8 L 21 17 A 2 2 0 0 1 19 19 L 5 19 A 2 2 0 0 1 3 17 L 3 8 A 2 2 0 0 1 5 6 Z M3 10h18M7 15h3") }
  val Recurring: ImageVector by lazy { lineIcon("M3 12a9 9 0 0 1 15-6.7L21 8M21 3v5h-5M21 12a9 9 0 0 1-15 6.7L3 16M3 21v-5h5") }
  val Debts: ImageVector by lazy { lineIcon("M17 11a4 4 0 1 0-8 0M5 21v-2a4 4 0 0 1 4-4h8a4 4 0 0 1 4 4v2 M 9 7 a 4 4 0 1 0 8 0 a 4 4 0 1 0 -8 0") }
  val Reports: ImageVector by lazy { lineIcon("M4 19V5M9 19V9M14 19v-6M19 19V3") }
  val Add: ImageVector by lazy { lineIcon("M12 5v14M5 12h14") }
  val Close: ImageVector by lazy { lineIcon("M6 6l12 12M18 6L6 18") }
  val Back: ImageVector by lazy { lineIcon("M15 18L9 12L15 6") }
  val Forward: ImageVector by lazy { lineIcon("M9 18L15 12L9 6") }
  val Settings: ImageVector by lazy { lineIcon("M 9 12 a 3 3 0 1 0 6 0 a 3 3 0 1 0 -6 0 M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 1 1-2.83 2.83l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-4 0v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 1 1-2.83-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1 0-4h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 1 1 2.83-2.83l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 4 0v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 1 1 2.83 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1z") }
  val Search: ImageVector by lazy { lineIcon("M 4 11 a 7 7 0 1 0 14 0 a 7 7 0 1 0 -14 0 M21 21l-4.3-4.3") }
  val Sort: ImageVector by lazy { lineIcon("M3 6h18M6 12h12M10 18h4") }
  val Edit: ImageVector by lazy { lineIcon("M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7 M18.5 2.5a2.12 2.12 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z") }
  val More: ImageVector by lazy { lineIcon("M 5 12 a 1 1 0 1 0 2 0 a 1 1 0 1 0 -2 0 M 11 12 a 1 1 0 1 0 2 0 a 1 1 0 1 0 -2 0 M 17 12 a 1 1 0 1 0 2 0 a 1 1 0 1 0 -2 0") }
  val History: ImageVector by lazy { lineIcon("M 3 12 a 9 9 0 1 0 18 0 a 9 9 0 1 0 -18 0 M12 7v5l3 2") }
  val Archive: ImageVector by lazy { lineIcon("M 4 4 L 20 4 A 1 1 0 0 1 21 5 L 21 7 A 1 1 0 0 1 20 8 L 4 8 A 1 1 0 0 1 3 7 L 3 5 A 1 1 0 0 1 4 4 Z M5 8v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V8M10 12h4") }
  val Pause: ImageVector by lazy { lineIcon("M 7 4 L 9 4 A 1 1 0 0 1 10 5 L 10 19 A 1 1 0 0 1 9 20 L 7 20 A 1 1 0 0 1 6 19 L 6 5 A 1 1 0 0 1 7 4 Z M 15 4 L 17 4 A 1 1 0 0 1 18 5 L 18 19 A 1 1 0 0 1 17 20 L 15 20 A 1 1 0 0 1 14 19 L 14 5 A 1 1 0 0 1 15 4 Z") }
  val Sparkle: ImageVector by lazy { lineIcon("M12 3l1.6 4.4L18 9l-4.4 1.6L12 15l-1.6-4.4L6 9l4.4-1.6L12 3z M19 14l.8 2.2L22 17l-2.2.8L19 20l-.8-2.2L16 17l2.2-.8L19 14z") }
  val Export: ImageVector by lazy { lineIcon("M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4M7 10l5 5 5-5M12 15V3") }
  val Upload: ImageVector by lazy { lineIcon("M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4M17 8l-5-5-5 5M12 3v12") }
  val Sliders: ImageVector by lazy { lineIcon("M 4 6 L 20 6 M 4 12 L 20 12 M 4 18 L 14 18") }
  val Check: ImageVector by lazy { lineIcon("M5 13l4 4L19 7") }
  val ArrowUp: ImageVector by lazy { lineIcon("M12 19V5M5 12l7-7 7 7") }
  val ArrowDown: ImageVector by lazy { lineIcon("M12 5v14M19 12l-7 7-7-7") }
  val ArrowRight: ImageVector by lazy { lineIcon("M5 12h14M13 5l7 7-7 7") }
  val TrendUp: ImageVector by lazy { lineIcon("M5 16L19 6M19 6H9M19 6V16") }
  val TrendDown: ImageVector by lazy { lineIcon("M5 8L19 18M19 18H9M19 18V8") }
  val Transfer: ImageVector by lazy { lineIcon("M3 8h14M14 5l3 3-3 3M21 16H7M10 13l-3 3 3 3") }
  val Backspace: ImageVector by lazy { lineIcon("M22 4H8L2 10l6 6h14a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2zM12 9l5 5M17 9l-5 5") }
  val Alert: ImageVector by lazy { lineIcon("M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z M 12 9 L 12 13 M 12 17 L 12.01 17") }
  val Info: ImageVector by lazy { lineIcon("M 3 12 a 9 9 0 1 0 18 0 a 9 9 0 1 0 -18 0 M 12 8 L 12 12 M 12 16 L 12.01 16") }
  val Bell: ImageVector by lazy { lineIcon("M18 8a6 6 0 0 0-12 0c0 7-3 9-3 9h18s-3-2-3-9 M13.73 21a2 2 0 0 1-3.46 0") }
  val Clock: ImageVector by lazy { lineIcon("M 3 12 a 9 9 0 1 0 18 0 a 9 9 0 1 0 -18 0 M 12 7 L 12 12 L 15 14") }
  val Person: ImageVector by lazy { lineIcon("M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2 M 8 7 a 4 4 0 1 0 8 0 a 4 4 0 1 0 -8 0") }
  val Calendar: ImageVector by lazy { lineIcon("M 5 5 L 19 5 A 2 2 0 0 1 21 7 L 21 19 A 2 2 0 0 1 19 21 L 5 21 A 2 2 0 0 1 3 19 L 3 7 A 2 2 0 0 1 5 5 Z M 3 10 L 21 10 M 8 3 L 8 7 M 16 3 L 16 7") }
  val Sun: ImageVector by lazy { lineIcon("M 8 12 a 4 4 0 1 0 8 0 a 4 4 0 1 0 -8 0 M12 2v2M12 20v2M4.93 4.93l1.41 1.41M17.66 17.66l1.41 1.41M2 12h2M20 12h2M4.93 19.07l1.41-1.41M17.66 6.34l1.41-1.41") }
  val Moon: ImageVector by lazy { lineIcon("M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z") }
  val Currency: ImageVector by lazy { lineIcon("M12 2v20M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6") }
  val Attach: ImageVector by lazy { lineIcon("M5 12h14 M12 5v14 M 6 3 L 18 3 A 3 3 0 0 1 21 6 L 21 18 A 3 3 0 0 1 18 21 L 6 21 A 3 3 0 0 1 3 18 L 3 6 A 3 3 0 0 1 6 3 Z") }
  val ChevronLeft: ImageVector by lazy { lineIcon("M15 18l-6-6 6-6") }
  val ChevronRight: ImageVector by lazy { lineIcon("M9 18l6-6-6-6") }
  val Bank: ImageVector by lazy { lineIcon("M3 21h18M3 10h18M5 6l7-3 7 3M4 10v11M20 10v11M8 14v3M12 14v3M16 14v3") }
  val Wallet: ImageVector by lazy { lineIcon("M20 12V8H6a2 2 0 0 1 0-4h12v4 M4 6v12c0 1.1.9 2 2 2h14v-4 M18 12a2 2 0 0 0 0 4h4v-4Z") }
  val Mobile: ImageVector by lazy { lineIcon("M 8 2 L 16 2 A 2 2 0 0 1 18 4 L 18 20 A 2 2 0 0 1 16 22 L 8 22 A 2 2 0 0 1 6 20 L 6 4 A 2 2 0 0 1 8 2 Z M 11 18 L 13 18") }
  val Food: ImageVector by lazy { lineIcon("M3 11h18M5 11a7 7 0 0 1 14 0M2 15h20M6 19h12") }
  val Groceries: ImageVector by lazy { lineIcon("M 8 20 a 1 1 0 1 0 2 0 a 1 1 0 1 0 -2 0 M 17 20 a 1 1 0 1 0 2 0 a 1 1 0 1 0 -2 0 M2 4h2.5l3 13h12L22 7H6") }
  val Rent: ImageVector by lazy { lineIcon("M3 11l9-8 9 8v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-9z M9 22V12h6v10") }
  val Utilities: ImageVector by lazy { lineIcon("M 13 2 L 3 14 L 12 14 L 11 22 L 21 10 L 12 10 L 13 2 Z") }
  val Transport: ImageVector by lazy { lineIcon("M5 17h14M6 17V9l2-4h8l2 4v8M8 13h8M7 17v2M17 17v2") }
  val Shopping: ImageVector by lazy { lineIcon("M6 2L3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4z M3 6h18M16 10a4 4 0 0 1-8 0") }
  val Entertainment: ImageVector by lazy { lineIcon("M 9 7 L 16 12 L 9 17 L 9 7 Z M 3 12 a 9 9 0 1 0 18 0 a 9 9 0 1 0 -18 0") }
  val PersonalCare: ImageVector by lazy { lineIcon("M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z") }
  val Subscriptions: ImageVector by lazy { lineIcon("M3 12a9 9 0 0 1 15-6.7L21 8M21 3v5h-5M21 12a9 9 0 0 1-15 6.7L3 16M3 21v-5h5") }
  val Healthcare: ImageVector by lazy { lineIcon("M 5 6 L 19 6 A 2 2 0 0 1 21 8 L 21 18 A 2 2 0 0 1 19 20 L 5 20 A 2 2 0 0 1 3 18 L 3 8 A 2 2 0 0 1 5 6 Z M12 10v6M9 13h6M8 6V4h8v2") }
  val Education: ImageVector by lazy { lineIcon("M22 10L12 5 2 10l10 5 10-5z M6 12v5c0 2 3 3 6 3s6-1 6-3v-5") }
  val Debt: ImageVector by lazy { lineIcon("M17 3l4 4-4 4M3 7h18M7 13l-4 4 4 4M21 17H3") }
  val Salary: ImageVector by lazy { lineIcon("M12 2v20M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6") }
  val Receipt: ImageVector by lazy { lineIcon("M6 2h9l4 4v16H6z M14 2v4h4 M9 12h6M9 16h4") }
  val Other: ImageVector by lazy { lineIcon("M 5 12 a 1 1 0 1 0 2 0 a 1 1 0 1 0 -2 0 M 11 12 a 1 1 0 1 0 2 0 a 1 1 0 1 0 -2 0 M 17 12 a 1 1 0 1 0 2 0 a 1 1 0 1 0 -2 0") }
  val Signal: ImageVector by lazy { lineIcon("M 1 6.5 L 3 6.5 A 0.5 0.5 0 0 1 3.5 7 L 3.5 10 A 0.5 0.5 0 0 1 3 10.5 L 1 10.5 A 0.5 0.5 0 0 1 0.5 10 L 0.5 7 A 0.5 0.5 0 0 1 1 6.5 Z M 5.5 4.5 L 7.5 4.5 A 0.5 0.5 0 0 1 8 5 L 8 10 A 0.5 0.5 0 0 1 7.5 10.5 L 5.5 10.5 A 0.5 0.5 0 0 1 5 10 L 5 5 A 0.5 0.5 0 0 1 5.5 4.5 Z M 10 2.5 L 12 2.5 A 0.5 0.5 0 0 1 12.5 3 L 12.5 10 A 0.5 0.5 0 0 1 12 10.5 L 10 10.5 A 0.5 0.5 0 0 1 9.5 10 L 9.5 3 A 0.5 0.5 0 0 1 10 2.5 Z M 14.5 0.5 L 16.5 0.5 A 0.5 0.5 0 0 1 17 1 L 17 10 A 0.5 0.5 0 0 1 16.5 10.5 L 14.5 10.5 A 0.5 0.5 0 0 1 14 10 L 14 1 A 0.5 0.5 0 0 1 14.5 0.5 Z") }
  val Wifi: ImageVector by lazy { lineIcon("M7.5 9.5L7.5 9.51 M4.5 7C5.36 6.18 6.4 5.75 7.5 5.75C8.6 5.75 9.64 6.18 10.5 7 M2 4.5C3.5 3 5.4 2.25 7.5 2.25C9.6 2.25 11.5 3 13 4.5") }
  val Battery: ImageVector by lazy { lineIcon("M 3.5 0.5 L 19.5 0.5 A 3 3 0 0 1 22.5 3.5 L 22.5 8.5 A 3 3 0 0 1 19.5 11.5 L 3.5 11.5 A 3 3 0 0 1 0.5 8.5 L 0.5 3.5 A 3 3 0 0 1 3.5 0.5 Z M 3.5 2 L 18.5 2 A 1.5 1.5 0 0 1 20 3.5 L 20 8.5 A 1.5 1.5 0 0 1 18.5 10 L 3.5 10 A 1.5 1.5 0 0 1 2 8.5 L 2 3.5 A 1.5 1.5 0 0 1 3.5 2 Z M 25 4 L 25 4 A 1 1 0 0 1 26 5 L 26 7 A 1 1 0 0 1 25 8 L 25 8 A 1 1 0 0 1 24 7 L 24 5 A 1 1 0 0 1 25 4 Z") }
}

private fun lineIcon(pathData: String): ImageVector =
  ImageVector.Builder(
    defaultWidth = 24.dp,
    defaultHeight = 24.dp,
    viewportWidth = 24f,
    viewportHeight = 24f,
  ).apply {
    addPath(
      pathData = PathParser().parsePathString(pathData).toNodes(),
      stroke = SolidColor(Color.White),
      strokeLineWidth = 1.5f,
      strokeLineCap = StrokeCap.Round,
      strokeLineJoin = StrokeJoin.Round,
    )
  }.build()

@Preview(name = "FlowFin icons", backgroundColor = 0xFF08080A, showBackground = true, widthDp = 360)
@Composable
private fun PreviewFlowFinIcons() = FlowFinTheme {
  val palette = FlowFinTheme.colors
  val all = listOf(
    "Home" to FlowFinIcons.Home,
    "Accounts" to FlowFinIcons.Accounts,
    "Recurring" to FlowFinIcons.Recurring,
    "Debts" to FlowFinIcons.Debts,
    "Reports" to FlowFinIcons.Reports,
    "Add" to FlowFinIcons.Add,
    "Close" to FlowFinIcons.Close,
    "Back" to FlowFinIcons.Back,
    "Forward" to FlowFinIcons.Forward,
    "Settings" to FlowFinIcons.Settings,
    "Search" to FlowFinIcons.Search,
    "Sort" to FlowFinIcons.Sort,
    "Edit" to FlowFinIcons.Edit,
    "More" to FlowFinIcons.More,
    "History" to FlowFinIcons.History,
    "Archive" to FlowFinIcons.Archive,
    "Pause" to FlowFinIcons.Pause,
    "Sparkle" to FlowFinIcons.Sparkle,
    "Export" to FlowFinIcons.Export,
    "Upload" to FlowFinIcons.Upload,
    "Sliders" to FlowFinIcons.Sliders,
    "Check" to FlowFinIcons.Check,
    "ArrowUp" to FlowFinIcons.ArrowUp,
    "ArrowDown" to FlowFinIcons.ArrowDown,
    "ArrowRight" to FlowFinIcons.ArrowRight,
    "TrendUp" to FlowFinIcons.TrendUp,
    "TrendDown" to FlowFinIcons.TrendDown,
    "Transfer" to FlowFinIcons.Transfer,
    "Backspace" to FlowFinIcons.Backspace,
    "Alert" to FlowFinIcons.Alert,
    "Info" to FlowFinIcons.Info,
    "Bell" to FlowFinIcons.Bell,
    "Clock" to FlowFinIcons.Clock,
    "Person" to FlowFinIcons.Person,
    "Calendar" to FlowFinIcons.Calendar,
    "Sun" to FlowFinIcons.Sun,
    "Moon" to FlowFinIcons.Moon,
    "Currency" to FlowFinIcons.Currency,
    "Attach" to FlowFinIcons.Attach,
    "ChevronLeft" to FlowFinIcons.ChevronLeft,
    "ChevronRight" to FlowFinIcons.ChevronRight,
    "Bank" to FlowFinIcons.Bank,
    "Wallet" to FlowFinIcons.Wallet,
    "Mobile" to FlowFinIcons.Mobile,
    "Food" to FlowFinIcons.Food,
    "Groceries" to FlowFinIcons.Groceries,
    "Rent" to FlowFinIcons.Rent,
    "Utilities" to FlowFinIcons.Utilities,
    "Transport" to FlowFinIcons.Transport,
    "Shopping" to FlowFinIcons.Shopping,
    "Entertainment" to FlowFinIcons.Entertainment,
    "PersonalCare" to FlowFinIcons.PersonalCare,
    "Subscriptions" to FlowFinIcons.Subscriptions,
    "Healthcare" to FlowFinIcons.Healthcare,
    "Education" to FlowFinIcons.Education,
    "Debt" to FlowFinIcons.Debt,
    "Salary" to FlowFinIcons.Salary,
    "Receipt" to FlowFinIcons.Receipt,
    "Other" to FlowFinIcons.Other,
    "Signal" to FlowFinIcons.Signal,
    "Wifi" to FlowFinIcons.Wifi,
    "Battery" to FlowFinIcons.Battery,
  )
  Column(
    modifier = Modifier.padding(16.dp),
    verticalArrangement = Arrangement.spacedBy(16.dp),
  ) {
    all.chunked(5).forEach { row ->
      Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
        row.forEach { (name, icon) ->
          Column(
            modifier = Modifier.width(60.dp),
            horizontalAlignment = Alignment.CenterHorizontally,
          ) {
            Icon(icon, contentDescription = name, tint = palette.text, modifier = Modifier.size(24.dp))
            Text(
              text = name,
              modifier = Modifier.padding(top = 6.dp),
              style = FlowFinTheme.typography.caption.copy(fontSize = 8.sp, letterSpacing = 0.04.em),
              color = palette.textMute,
              textAlign = TextAlign.Center,
              maxLines = 1,
              overflow = TextOverflow.Ellipsis,
            )
          }
        }
      }
    }
  }
}
