#!/usr/bin/env python3
"""Generate FlowFinIcons.kt from the design-system icon sheet.

Reads the line-icon SVGs in ``design/system/icons.html`` and emits a Kotlin
object of stroke ``ImageVector``s (plus a ``@Preview`` grid) at
``core/designsystem/src/main/kotlin/com/flowfin/core/designsystem/icon/FlowFinIcons.kt``.

Each SVG primitive (``path`` / ``circle`` / ``rect`` / ``line`` / ``polyline`` /
``polygon``) is converted to SVG path data and concatenated into one path per
icon; ImageVector renders it as a 1.5dp round stroke with no fill. The stroke
uses an opaque placeholder color that ``Icon(tint = …)`` recolors.

Usage::

    python3 design/tools/gen_flowfin_icons.py            # write the file
    python3 design/tools/gen_flowfin_icons.py --check     # parse + summarize only

This script is the source of truth for the icon set: re-running it overwrites the
generated file (doc comment included), so make changes here, not there. The HTML
is parsed with a few narrow regexes — it relies on each icon being one
``<svg>…</svg>`` immediately followed by its ``<div class="icon-cell-name">``.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
SRC = REPO / "design" / "system" / "icons.html"
DST = (
    REPO
    / "core/designsystem/src/main/kotlin/com/flowfin/core/designsystem/icon/FlowFinIcons.kt"
)

# Override the auto-derived Kotlin name for a raw icon-cell-name, when a clearer
# name is wanted. Empty today — the derivation below already yields clean names.
OVERRIDES: dict[str, str] = {}

OBJECT_KDOC = """\
/**
 * FlowFin's icon language: thin line icons, deliberately not Material's filled
 * glyphs. Prefer these everywhere — resolved from category/account keys by
 * `categoryIcon()` in core/ui, or referenced directly for UI glyphs — and reach
 * for Material only when this set doesn't yet cover an icon.
 *
 * Each is a 24×24 stroke [ImageVector] (1.5dp, round caps/joins, no fill), drawn
 * to match the SVGs in design/system/icons.html. The stroke is an opaque
 * placeholder color, so an icon must be rendered through [Icon] for its `tint`
 * to apply; drawn untinted it shows the placeholder, not the color you intended.
 *
 * Generated by design/tools/gen_flowfin_icons.py — re-running it overwrites this
 * file, comment included, so make changes there (or keep them in sync).
 */"""

Icon = tuple[str, str, str]  # (kotlin name, source label, path data)


def num(value: str | float) -> str:
    """Format a coordinate the way SVG does — trim trailing zeros."""
    return f"{float(value):g}"


def attrs(tag_body: str) -> dict[str, str]:
    return dict(re.findall(r'(\w[\w-]*)\s*=\s*"([^"]*)"', tag_body))


def points_to_path(points: str, close: bool) -> str:
    coords = re.split(r"[\s,]+", points.strip())
    pairs = [f"{coords[i]} {coords[i + 1]}" for i in range(0, len(coords) - 1, 2)]
    return "M " + " L ".join(pairs) + (" Z" if close else "")


def rect_to_path(a: dict[str, str]) -> str:
    x, y = float(a.get("x", 0)), float(a.get("y", 0))
    w, h = float(a["width"]), float(a["height"])
    rx = float(a["rx"]) if "rx" in a else float(a.get("ry", 0))
    ry = float(a["ry"]) if "ry" in a else rx
    if rx <= 0:
        return f"M {num(x)} {num(y)} L {num(x + w)} {num(y)} L {num(x + w)} {num(y + h)} L {num(x)} {num(y + h)} Z"
    return (
        f"M {num(x + rx)} {num(y)} "
        f"L {num(x + w - rx)} {num(y)} A {num(rx)} {num(ry)} 0 0 1 {num(x + w)} {num(y + ry)} "
        f"L {num(x + w)} {num(y + h - ry)} A {num(rx)} {num(ry)} 0 0 1 {num(x + w - rx)} {num(y + h)} "
        f"L {num(x + rx)} {num(y + h)} A {num(rx)} {num(ry)} 0 0 1 {num(x)} {num(y + h - ry)} "
        f"L {num(x)} {num(y + ry)} A {num(rx)} {num(ry)} 0 0 1 {num(x + rx)} {num(y)} Z"
    )


def circle_to_path(a: dict[str, str]) -> str:
    cx, cy, r = float(a["cx"]), float(a["cy"]), float(a["r"])
    # Two half-arc sweeps, the standard circle-as-path trick.
    return (
        f"M {num(cx - r)} {num(cy)} "
        f"a {num(r)} {num(r)} 0 1 0 {num(2 * r)} 0 "
        f"a {num(r)} {num(r)} 0 1 0 {num(-2 * r)} 0"
    )


def line_to_path(a: dict[str, str]) -> str:
    return f"M {num(a['x1'])} {num(a['y1'])} L {num(a['x2'])} {num(a['y2'])}"


def svg_to_path_data(inner: str, label: str) -> str:
    parts: list[str] = []
    for tag, body in re.findall(r"<(path|circle|rect|line|polyline|polygon)\b([^>]*)>", inner):
        a = attrs(body)
        if tag == "path":
            d = a.get("d", "").strip()
            if not d:
                raise ValueError(f"icon {label!r}: <path> without a d attribute")
            parts.append(d)
        elif tag == "circle":
            parts.append(circle_to_path(a))
        elif tag == "rect":
            parts.append(rect_to_path(a))
        elif tag == "line":
            parts.append(line_to_path(a))
        elif tag == "polyline":
            parts.append(points_to_path(a["points"], close=False))
        elif tag == "polygon":
            parts.append(points_to_path(a["points"], close=True))
    if not parts:
        raise ValueError(f"icon {label!r}: no drawable primitives found")
    return re.sub(r"\s+", " ", " ".join(parts)).strip()


def to_identifier(label: str) -> str:
    if label in OVERRIDES:
        return OVERRIDES[label]
    name = re.sub(r"<[^>]+>", " ", label)  # drop <br> etc.
    name = name.split("/")[0]              # first variant of "a / b"
    name = name.split("(")[0]              # drop "(income)"-style qualifiers
    tokens = re.split(r"[^a-zA-Z0-9]+", name)
    return "".join(t[:1].upper() + t[1:] for t in tokens if t)


def parse_icons(html: str) -> list[Icon]:
    pairs = re.findall(
        r'<svg[^>]*>(.*?)</svg>\s*<div class="icon-cell-name">(.*?)</div>',
        html,
        re.S,
    )
    icons: list[Icon] = []
    used: set[str] = set()
    for inner, raw_label in pairs:
        label = re.sub(r"\s+", " ", raw_label.replace("&amp;", "&")).strip()
        name = to_identifier(raw_label)
        if name in used:
            print(f"  skip duplicate identifier {name!r} (from {label!r})", file=sys.stderr)
            continue
        used.add(name)
        icons.append((name, label, svg_to_path_data(inner, label)))
    return icons


def render_kotlin(icons: list[Icon]) -> str:
    vals = "\n".join(f'  val {name}: ImageVector by lazy {{ lineIcon("{d}") }}' for name, _, d in icons)
    entries = "\n".join(f'    "{name}" to FlowFinIcons.{name},' for name, _, _ in icons)
    return f"""package com.flowfin.core.designsystem.icon

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.material3.Icon
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.em
import androidx.compose.ui.unit.sp
import com.flowfin.core.designsystem.theme.FlowFinTheme

{OBJECT_KDOC}
object FlowFinIcons {{
{vals}
}}

private fun lineIcon(pathData: String): ImageVector =
  ImageVector.Builder(
    defaultWidth = 24.dp,
    defaultHeight = 24.dp,
    viewportWidth = 24f,
    viewportHeight = 24f,
  ).apply {{
    addPath(
      pathData = PathParser().parsePathString(pathData).toNodes(),
      stroke = SolidColor(Color.White),
      strokeLineWidth = 1.5f,
      strokeLineCap = StrokeCap.Round,
      strokeLineJoin = StrokeJoin.Round,
    )
  }}.build()

@Preview(name = "FlowFin icons", backgroundColor = 0xFF08080A, showBackground = true, widthDp = 360)
@Composable
private fun PreviewFlowFinIcons() = FlowFinTheme {{
  val palette = FlowFinTheme.colors
  val all = listOf(
{entries}
  )
  Column(
    modifier = Modifier.padding(16.dp),
    verticalArrangement = Arrangement.spacedBy(16.dp),
  ) {{
    all.chunked(5).forEach {{ row ->
      Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {{
        row.forEach {{ (name, icon) ->
          Column(
            modifier = Modifier.width(60.dp),
            horizontalAlignment = Alignment.CenterHorizontally,
          ) {{
            Icon(icon, contentDescription = name, tint = palette.text, modifier = Modifier.size(24.dp))
            Text(
              text = name,
              modifier = Modifier.padding(top = 6.dp),
              style = FlowFinTheme.typography.caption.copy(fontSize = 8.sp, letterSpacing = 0.04.em),
              color = palette.textMute,
              textAlign = TextAlign.Center,
              maxLines = 1,
              overflow = TextOverflow.Ellipsis,
            )
          }}
        }}
      }}
    }}
  }}
}}
"""


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate FlowFinIcons.kt from icons.html")
    parser.add_argument("--check", action="store_true", help="parse and summarize, don't write")
    args = parser.parse_args()

    if not SRC.exists():
        print(f"error: source not found: {SRC}", file=sys.stderr)
        return 1

    icons = parse_icons(SRC.read_text())
    print(f"{len(icons)} icons parsed from {SRC.relative_to(REPO)}")
    for name, label, _ in icons:
        print(f"  {name:16s} <- {label}")

    if args.check:
        return 0

    DST.write_text(render_kotlin(icons))
    print(f"wrote {DST.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
