#!/usr/bin/env python3
"""Generate the launcher icon from the brand monogram.

design/system/brand.html specifies the app icon as "the monogram lifted onto a
brushed cream tile". The glyph here is not traced by hand: it is the real
Literata italic "v" pulled out of the font the app already ships, instantiated
at the weight and optical size the brand sets, so the icon and the wordmark are
the same letterform.

    pip install fonttools && python3 design/tools/gen_app_icon.py

Writes the three adaptive-icon layers into app/src/main/res/drawable/.
"""
import pathlib
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.boundsPen import BoundsPen

ROOT = pathlib.Path(__file__).resolve().parents[2]
FONT = ROOT / "core/designsystem/src/main/res/font/literata_italic.ttf"
OUT = ROOT / "app/src/main/res/drawable"

# From design/system/brand.html.
WGHT, OPSZ = 400, 72                              # .app-icon .glyph
INK = "#FF1A1A1F"                                 # glyph on the cream tile
CREAM = ("#FFE8DCC0", "#FFD8C49C", "#FFC9B383")   # the 160deg tile gradient

# Adaptive-icon canvas is 108dp, of which a launcher's mask shows the middle
# 72dp. The mark is sized against 72: against 108 it would tower over every
# other icon on the home screen.
CANVAS, MASK = 108.0, 72.0
GLYPH_TO_TILE = 0.36        # v height as a share of the visible tile
DOT_EM, GAP_EM = 0.125, 0.05    # the brand's 10px dot and 4px gap, at 80px

HEADER = (
    '<?xml version="1.0" encoding="utf-8"?>\n'
    '<!-- Generated by design/tools/gen_app_icon.py. Do not hand-edit;\n'
    '     edit the generator and re-run it. -->\n'
)


def geometry():
    """The v path, the transform that lands it on the canvas, and the dot."""
    font = instancer.instantiateVariableFont(
        TTFont(FONT), {"wght": WGHT, "opsz": OPSZ}, inplace=False
    )
    glyphs = font.getGlyphSet()
    name = font.getBestCmap()[ord("v")]
    bounds = BoundsPen(glyphs)
    glyphs[name].draw(bounds)
    pen = SVGPathPen(glyphs)
    glyphs[name].draw(pen)

    x0, y0, x1, y1 = bounds.bounds
    upem = font["head"].unitsPerEm

    target_h = GLYPH_TO_TILE * MASK
    scale = target_h / (y1 - y0)
    em = upem * scale

    v_w = (x1 - x0) * scale
    dot_d, gap = DOT_EM * em, GAP_EM * em
    left = (CANVAS - (v_w + gap + dot_d)) / 2.0
    baseline = (CANVAS - target_h) / 2.0 + y1 * scale

    r = dot_d / 2.0
    cx = left + v_w + gap + r
    cy = baseline - r
    dot = (
        f"M{cx - r:.3f},{cy:.3f}"
        f"a{r:.3f},{r:.3f} 0 1,0 {dot_d:.3f},0"
        f"a{r:.3f},{r:.3f} 0 1,0 {-dot_d:.3f},0z"
    )
    # A VectorDrawable group with pivot 0,0 applies translate * scale, so a
    # negative scaleY is exactly the flip from font coordinates (y up) to
    # canvas coordinates (y down).
    return pen.getCommands(), scale, left - x0 * scale, baseline, dot


def vector(body, aapt=False):
    ns = '\n    xmlns:aapt="http://schemas.android.com/aapt"' if aapt else ""
    return (
        f"{HEADER}"
        f'<vector xmlns:android="http://schemas.android.com/apk/res/android"{ns}\n'
        f'    android:width="{CANVAS:.0f}dp"\n'
        f'    android:height="{CANVAS:.0f}dp"\n'
        f'    android:viewportWidth="{CANVAS:.0f}"\n'
        f'    android:viewportHeight="{CANVAS:.0f}">\n'
        f"{body}"
        "</vector>\n"
    )


def mark(colour, d, scale, tx, ty, dot):
    return vector(
        f'  <group\n'
        f'      android:scaleX="{scale:.6f}"\n'
        f'      android:scaleY="{-scale:.6f}"\n'
        f'      android:translateX="{tx:.4f}"\n'
        f'      android:translateY="{ty:.4f}">\n'
        f'    <path android:fillColor="{colour}" android:pathData="{d}" />\n'
        f'  </group>\n'
        f'  <path android:fillColor="{colour}" android:pathData="{dot}" />\n'
    )


def main():
    d, scale, tx, ty, dot = geometry()

    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "ic_launcher_background.xml").write_text(
        vector(
            '  <path android:pathData="M0,0h108v108h-108z">\n'
            '    <aapt:attr name="android:fillColor">\n'
            '      <gradient android:type="linear"\n'
            '          android:startX="30.3" android:startY="-11"\n'
            '          android:endX="77.7" android:endY="119">\n'
            f'        <item android:offset="0" android:color="{CREAM[0]}" />\n'
            f'        <item android:offset="0.7" android:color="{CREAM[1]}" />\n'
            f'        <item android:offset="1" android:color="{CREAM[2]}" />\n'
            '      </gradient>\n'
            '    </aapt:attr>\n'
            '  </path>\n',
            aapt=True,
        )
    )
    (OUT / "ic_launcher_foreground.xml").write_text(mark(INK, d, scale, tx, ty, dot))
    # Themed icons: the system supplies the colour, so this layer only has to
    # carry the right shape.
    (OUT / "ic_launcher_monochrome.xml").write_text(
        mark("#FF000000", d, scale, tx, ty, dot)
    )
    print(f"v height {GLYPH_TO_TILE * MASK:.1f}dp, scale {scale:.6f}")
    print("wrote", ", ".join(p.name for p in sorted(OUT.glob("ic_launcher_*.xml"))))


if __name__ == "__main__":
    main()
